### ISSUE TITLE
image-perceiver pod is being created when running on Minikube

### ISSUE THREAD

**Issue by jlin963** [blackducksoftware/perceptor-protoform#47]
Setup: minikube version: v0.25.2, install w/ protoform kube1.6

An image-perceiver pod is being created and deployed when I install OpsSight on Minikube, but it shouldn't be since its purpose is to monitor image streams and Kube doesn't have those.  

![screen shot 2018-04-02 at 2 04 40 pm](https://user-images.githubusercontent.com/31659508/38208365-d63f4948-367e-11e8-9946-95f056e35d47.png)

**Comment by msenmurugan** [comment]
While installing, please don't use -i option. Not a bug.
