### ISSUE TITLE
change perceptor config map option

### ISSUE THREAD

**Issue by mattfenwick** [blackducksoftware/perceptor-protoform#88]
For the Perceptor config map:

change `HubClientTimeoutSeconds` to `HubClientTimeoutMilliseconds`, and change the values accordingly (multiply by 1000).

**Comment by mattfenwick** [comment]
[Here's](https://github.com/blackducksoftware/perceptor/blob/master/pkg/core/config.go#L35) the config map type.

**Comment by rrati** [comment]
Fixedin #90
