### ISSUE TITLE
Config map changes

### ISSUE THREAD

**Issue by mattfenwick** [blackducksoftware/perceptor-protoform#96]
Config maps for some of the containers have changed:

 - imagefacade
   - [ ] add `ImageDirectory: string` -- this is the path for the mounted directory, into which pulled images will be saved
   - [x] remove `DockerUser`
   - [x] remove `DockerPassword`
   - [x] remove `InternalDockerRegistries`
   - [x] add `PrivateDockerRegistries: []struct {Url string; User string; Password string}`

 - scanner
   - [ ] add `ImageDirectory: string` -- this is the path for the mounted directory, which pulled images will be read from.  Must match imagefacade's value

 - perceptor

**Comment by msenmurugan** [comment]
@mattfenwick do we need Image Directory in both Image facade and scanner?
